"""baseline: схема до Alembic (businesses, products, receipts, receipt_items, expenses, daily_metrics)

Revision ID: 0001
Revises: 
Create Date: 2026-06-12 22:05:58.164082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('evotor_store_uuid', sa.String(length=100), nullable=True),
    sa.Column('business_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('equipment_value', sa.Numeric(precision=12, scale=2), nullable=True),
    # автогенерация на SQLite дала '(CURRENT_TIMESTAMP)' — без скобок валидно и там, и в Postgres
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_evotor_store_uuid'), 'businesses', ['evotor_store_uuid'], unique=True)
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('operating_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_check', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('checks_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_metrics_metric_date'), 'daily_metrics', ['metric_date'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('COGS', 'RENT', 'UTILITIES', 'PAYROLL', 'TAXES', 'MARKETING', 'ACQUIRING', 'SOFTWARE', 'COMMS_SECURITY', 'OTHER', 'DEPRECIATION', name='expensecategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_period'), 'expenses', ['period'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('evotor_uuid', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sell_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_evotor_uuid'), 'products', ['evotor_uuid'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('receipt_uuid', sa.String(length=100), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=False),
    sa.Column('total_sum', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('cashier', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_receipt_uuid'), 'receipts', ['receipt_uuid'], unique=True)
    op.create_index(op.f('ix_receipts_sold_at'), 'receipts', ['sold_at'], unique=False)
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_items')
    op.drop_index(op.f('ix_receipts_sold_at'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_receipt_uuid'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_products_evotor_uuid'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_expenses_period'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_daily_metrics_metric_date'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_businesses_evotor_store_uuid'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
